### ISSUE TITLE
Using srcType on C#

### ISSUE THREAD

**Issue by glGarg** [srcML/srcType#6]
Since I couldn't find any documentation on this, I wanted to confirm whether or not srcType works on C# code.

I was actually able to get it to run on some C# code, but noticed that it wasn't pulling information on C# specific constructs correctly like the return types of property getters and setters. I'm guessing the reason why it ran was not because C# is supported, but purely because it's syntactically similar to C++.

Any info on this would be great.

Thanks!

**Comment by cnewman** [comment]
It doesn't support C# directly, no. It could be modified to support C# and it probably wouldn't  be too hard to implement. Unfortunately, time is the limiting factor at the moment. Let me know if you would like to try and I will provide some instructions on where to look/what to change.
